Fix: Stuff Management
Soft-Craft-Tech/pamba-web-client pull request #49
Opened 2024-06-03 21:47 UTC by sonylomo

## Description

- Implement edit stuff feature and populate the data to be edited on the form
- Removed redundant column filters 
- Form value reset on form submission and query invalidation for _all stuff details_ 

## Motivation and Context

- Fixes issue #[KAN-27](https://pamba-africa.atlassian.net/browse/KAN-27?atlOrigin=eyJpIjoiNGFhMWJmNGJlNTY4NDhmMTg4OTZkNmQzMmJmMWY0OTAiLCJwIjoiaiJ9)

## How Has This Been Tested?

- Tested edit, delete and creation actions locally

## Screenshots (if appropriate):

- N/A

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2024-06-04 09:32 UTC, daveclinton requested changes

2024-06-04 09:32 UTC, daveclinton commented on .gitignore
> +.env
we are using the env.local
why add the extra file?

2024-06-04 09:32 UTC, daveclinton commented on app/api/requests.ts
> +  return useMutation<void, Error, any>(async ([expenxeId, formData]) => {
add a appropriate response type

2024-06-04 09:32 UTC, daveclinton commented on app/api/requests.ts
> +  return useMutation<void, Error, any>(async ({ f_name, phone, role }) => {
add appropriate payload type

2024-06-04 09:32 UTC, daveclinton commented on app/api/requests.ts
> +  return useMutation<void, Error, any>(
add appropriate response type

2024-06-04 09:32 UTC, daveclinton commented on app/api/requests.ts
> +  const queryClient = useQueryClient();
do we need to cache a query here? Or what is the query client for here?

2024-06-04 09:33 UTC, daveclinton commented
You should also create your feature branch off release branch @sonylomo

2024-06-10 15:53 UTC, McbullIan approved these changes
LGTM

2024-06-12 09:13 UTC, regan-mu submitted a review, later dismissed

2024-06-12 09:53 UTC, daveclinton approved these changes

2024-06-12 10:27 UTC, merged